### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by internethering** [paspo/roundcube_export_provisioning#1]
Hi, please make you plugin php7 compatbile. I think updating composer.json should be enough, because it works with php7 on my installation :)

**Comment by paspo** [comment]
I also tested it with PHP7, and it works. I'll create a new release with the correct composer.json.
But the point is: PHP7 support in roundcube is still buggy...

**Comment by internethering** [comment]
mmh, dosn't work with newer minor -versions:

```
 - paspo/export_provisioning dev-master requires php >=5.3,<=7.0 -> your PHP version (7.0.2-pl0-gentoo) or "config.platform.php" value does not satisfy that requirement.
```
