### ISSUE TITLE
PHP7 compatibility again :)

### ISSUE THREAD

**Issue by internethering** [paspo/roundcube_export_provisioning#2]
mmh, github should allow to reopen bugs :) your fix dosn't work with newer minor-versions:

```
 - paspo/export_provisioning dev-master requires php >=5.3,<=7.0 -> your PHP version (7.0.2-pl0-gentoo) or "config.platform.php" value does not satisfy that requirement.
```

I think it is safe to remove the upper limit. If there are problems with newer php versions in the future, I'll going to open an issue ;)

**Comment by paspo** [comment]
totally agree, I'll remove the upper limit
