### ISSUE TITLE
Feature suggestion: editable port numbers

### ISSUE THREAD

**Issue by florianbeer** [paspo/roundcube_export_provisioning#4]
I'd like to have a way to influence the port numbers of incoming and outgoing servers in the export profile. In my case the profile for example lists port 25 for SMTP and 143 for IMAP, I encourage all of my customers to use the submission port on 587 and IMAP via TLS on 993 though.

Taking a quick look at the code I couldn't figure out where it derives those values from. Maybe it would be an option to add config settings to alter these values?

Thanks for your work, this plugin could be quite useful and reduce the amount of times I have to walk people through setting up their mail clients properly on the phone.

**Comment by paspo** [comment]
(sorry for late reply)
Profiles are generated using Roundcube configuration, so there's no need to customize ports (if you're exporting a configuration profile, you're already logged)

**Comment by florianbeer** [comment]
Roundcube uses a different port because of imapproxy (to work around opening a new connection for every "click" on the website) and since it is on the same host as the SMTP server, 25 is used internally. Both ports do not apply to my customers, so using the config settings for profiles doesn't work at all.

**Comment by paspo** [comment]
Maybe the best solution is a dedicated config file (for this plugin only) where you can set alternative ports...

**Comment by paspo** [comment]
Please check if c7c8c1b4117a4cbdc605e51276c07076f3638faa is ok for you.

**Comment by florianbeer** [comment]
Splendid! Thank you very much. I'll give it a go as soon as possible, but looking at the source it seems this is exactly what I was thinking about.
