### ISSUE TITLE
On mobile phones, or small browser windows the Download link is not reachable.

### ISSUE THREAD

**Issue by MacLemon** [paspo/roundcube_export_provisioning#9]
## Summary:
When using Roundcube on a small screen, like a mobile phone, or in a narrow browser window, the link to actually download the configuration profile is not reachable since it is outside the viewport.

Same goes for the identity selection pupup-menu. (Which is less of a problem when there is only a single identity available.)

## Steps to Reproduce:
Visit your webmail instance with a mobile phone and try to download a provisioning profile.

## Expected Results:
Download link should be reachable.

## Actual Results:
Download link is always outside the viewport and cannot be reached. Not even when trying to zoom in or rotating the device as the viewport is fixed. Notice that there are no horizontal scrollbars and scrolling horizontally is actually not possible.

### Screenshots:
![img_0162-2](https://user-images.githubusercontent.com/90635/54040202-164cb780-41c5-11e9-9fc8-b40e1b9e8e11.png)
Standard portrait orientation.

![img_0163-2](https://user-images.githubusercontent.com/90635/54040213-1cdb2f00-41c5-11e9-9332-89a86118508f.png)
Portrait orientation when trying to zoom in to get to the download link.

![img_0164-2](https://user-images.githubusercontent.com/90635/54040214-219fe300-41c5-11e9-8c02-6fda0b71a844.png)
Landscape orientation to make the display wider, but still not enough to get to the download links.

## Regression:
n/a

## Notes:
I'm aware that the current default Roundcube theme “larry” is not suitable for mobile devices and that an the upcoming roundcube 1.4 is supposedly adding a more mobile friendly theme option. (Unknown to me when that release should become available though.)

## Possible Remedy
Making the text `Download provisioning (configuration) profile for iOS / OSX` a direct link to the download, keeping the same descriptive text. Same for `Download provisioning (configuration) profile for Outlook Express / Windows Live Mail`.

One could keep the current Download links as they are.

Replace `Choose the identity to export` with the Identity to export. (And maybe get rid of the popup at all if there's only a single identity to export which would make the interface even more simple to use.)

## Version Information:
- Roundcube 1.3.8
- export_provisioning (master and test-simplexml-req branches)

**Comment by paspo** [comment]
please check if branch [download-links](https://github.com/paspo/roundcube_export_provisioning/tree/dev-download-links) fixes it.

**Comment by ticoombs** [comment]
Confirming this branch fixes the issues I was also having. (My users thank you)

- Roundcube v1.3.4
